export const NOTIFY_MUSIC_DOWNLOAD_INIT = 'NOTIFY_MUSIC_DOWNLOAD_INIT';
export const NOTIFY_MUSIC_DOWNLOAD_PROGRESS = 'NOTIFY_MUSIC_DOWNLOAD_PROGRESS';
export const NOTIFY_MUSIC_DOWNLOADED = 'NOTIFY_MUSIC_DOWNLOADED';
export const NOTIFY_MUSIC_DOWNLOAD_COMPLETE = 'NOTIFY_MUSIC_DOWNLOAD_COMPLETE';
